extends: eslint:recommended
env:
  browser: true
  node: true
  es6: true
rules:
  no-console: off
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    modules: true